name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    name: Setup and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Run Tests
        uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
        with:
          run-coverage: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
